deployment:
  tasks:
    - export BASE_PATH=/home4/eccwogmy
    - export DEPLOY_PATH=$BASE_PATH/public_html/
    - cd $BASE_PATH/repositories/bymiguelbravo/ && npm run build
    - /bin/cp -R $BASE_PATH/repositories/bymiguelbravo/build/* $DEPLOY_PATH
